with-expecter: true
packages:
    github.com/evgeny-tokarev/office_app/backend/internal/repositories/office_repository:
      config:
        filename: "mock_{{.InterfaceName}}.go"
        dir: "mocks"
        mockname: "Mock{{.InterfaceName}}"
        outpkg: "mocks"
      interfaces:
        Querier:
    github.com/evgeny-tokarev/office_app/backend/internal/repositories/employee_repository:
      config:
        filename: "mock_{{.InterfaceName}}.go"
        dir: "mocks"
        mockname: "Mock{{.InterfaceName}}"
        outpkg: "mocks"
      interfaces:
        Store:
    github.com/evgeny-tokarev/office_app/backend/internal/repositories/user_repository:
      config:
        filename: "mock_{{.InterfaceName}}.go"
        dir: "mocks"
        mockname: "Mock{{.InterfaceName}}"
        outpkg: "mocks"
      interfaces:
        Store:
