version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=${SERVER_PORT}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB_NAME}
      - TOKEN_SECRET=${TOKEN_SECRET}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
#    environment:
    # Add frontend environment variables as needed

  lesson4-db:
    image: postgres:12
    restart: always
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PWD}
    - POSTGRES_DB=${PG_DB_NAME}
