// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	employee_repository "github.com/evgeny-tokarev/office_app/backend/internal/repositories/employee_repository"
	mock "github.com/stretchr/testify/mock"
)

// MockEmployee is an autogenerated mock type for the Store type
type MockEmployee struct {
	mock.Mock
}

type MockEmployee_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmployee) EXPECT() *MockEmployee_Expecter {
	return &MockEmployee_Expecter{mock: &_m.Mock}
}

// AttachePhoto provides a mock function with given fields: ctx, arg
func (_m *MockEmployee) AttachePhoto(ctx context.Context, arg employee_repository.AttachePhotoParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AttachePhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.AttachePhotoParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmployee_AttachePhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachePhoto'
type MockEmployee_AttachePhoto_Call struct {
	*mock.Call
}

// AttachePhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - arg employee_repository.AttachePhotoParams
func (_e *MockEmployee_Expecter) AttachePhoto(ctx interface{}, arg interface{}) *MockEmployee_AttachePhoto_Call {
	return &MockEmployee_AttachePhoto_Call{Call: _e.mock.On("AttachePhoto", ctx, arg)}
}

func (_c *MockEmployee_AttachePhoto_Call) Run(run func(ctx context.Context, arg employee_repository.AttachePhotoParams)) *MockEmployee_AttachePhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(employee_repository.AttachePhotoParams))
	})
	return _c
}

func (_c *MockEmployee_AttachePhoto_Call) Return(_a0 error) *MockEmployee_AttachePhoto_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmployee_AttachePhoto_Call) RunAndReturn(run func(context.Context, employee_repository.AttachePhotoParams) error) *MockEmployee_AttachePhoto_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmployee provides a mock function with given fields: ctx, arg
func (_m *MockEmployee) CreateEmployee(ctx context.Context, arg employee_repository.CreateEmployeeParams) (employee_repository.Employee, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmployee")
	}

	var r0 employee_repository.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.CreateEmployeeParams) (employee_repository.Employee, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.CreateEmployeeParams) employee_repository.Employee); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(employee_repository.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, employee_repository.CreateEmployeeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployee_CreateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmployee'
type MockEmployee_CreateEmployee_Call struct {
	*mock.Call
}

// CreateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - arg employee_repository.CreateEmployeeParams
func (_e *MockEmployee_Expecter) CreateEmployee(ctx interface{}, arg interface{}) *MockEmployee_CreateEmployee_Call {
	return &MockEmployee_CreateEmployee_Call{Call: _e.mock.On("CreateEmployee", ctx, arg)}
}

func (_c *MockEmployee_CreateEmployee_Call) Run(run func(ctx context.Context, arg employee_repository.CreateEmployeeParams)) *MockEmployee_CreateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(employee_repository.CreateEmployeeParams))
	})
	return _c
}

func (_c *MockEmployee_CreateEmployee_Call) Return(_a0 employee_repository.Employee, _a1 error) *MockEmployee_CreateEmployee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployee_CreateEmployee_Call) RunAndReturn(run func(context.Context, employee_repository.CreateEmployeeParams) (employee_repository.Employee, error)) *MockEmployee_CreateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEmployee provides a mock function with given fields: ctx, id
func (_m *MockEmployee) DeleteEmployee(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmployee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmployee_DeleteEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmployee'
type MockEmployee_DeleteEmployee_Call struct {
	*mock.Call
}

// DeleteEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEmployee_Expecter) DeleteEmployee(ctx interface{}, id interface{}) *MockEmployee_DeleteEmployee_Call {
	return &MockEmployee_DeleteEmployee_Call{Call: _e.mock.On("DeleteEmployee", ctx, id)}
}

func (_c *MockEmployee_DeleteEmployee_Call) Run(run func(ctx context.Context, id int64)) *MockEmployee_DeleteEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEmployee_DeleteEmployee_Call) Return(_a0 error) *MockEmployee_DeleteEmployee_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmployee_DeleteEmployee_Call) RunAndReturn(run func(context.Context, int64) error) *MockEmployee_DeleteEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmployee provides a mock function with given fields: ctx, id
func (_m *MockEmployee) GetEmployee(ctx context.Context, id int64) (employee_repository.Employee, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployee")
	}

	var r0 employee_repository.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (employee_repository.Employee, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) employee_repository.Employee); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(employee_repository.Employee)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployee_GetEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmployee'
type MockEmployee_GetEmployee_Call struct {
	*mock.Call
}

// GetEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEmployee_Expecter) GetEmployee(ctx interface{}, id interface{}) *MockEmployee_GetEmployee_Call {
	return &MockEmployee_GetEmployee_Call{Call: _e.mock.On("GetEmployee", ctx, id)}
}

func (_c *MockEmployee_GetEmployee_Call) Run(run func(ctx context.Context, id int64)) *MockEmployee_GetEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEmployee_GetEmployee_Call) Return(_a0 employee_repository.Employee, _a1 error) *MockEmployee_GetEmployee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployee_GetEmployee_Call) RunAndReturn(run func(context.Context, int64) (employee_repository.Employee, error)) *MockEmployee_GetEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// GetImagePath provides a mock function with given fields: ctx, id
func (_m *MockEmployee) GetImagePath(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImagePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployee_GetImagePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImagePath'
type MockEmployee_GetImagePath_Call struct {
	*mock.Call
}

// GetImagePath is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockEmployee_Expecter) GetImagePath(ctx interface{}, id interface{}) *MockEmployee_GetImagePath_Call {
	return &MockEmployee_GetImagePath_Call{Call: _e.mock.On("GetImagePath", ctx, id)}
}

func (_c *MockEmployee_GetImagePath_Call) Run(run func(ctx context.Context, id int64)) *MockEmployee_GetImagePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEmployee_GetImagePath_Call) Return(_a0 string, _a1 error) *MockEmployee_GetImagePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployee_GetImagePath_Call) RunAndReturn(run func(context.Context, int64) (string, error)) *MockEmployee_GetImagePath_Call {
	_c.Call.Return(run)
	return _c
}

// ListEmployees provides a mock function with given fields: ctx, officeID
func (_m *MockEmployee) ListEmployees(ctx context.Context, officeID int64) ([]employee_repository.Employee, error) {
	ret := _m.Called(ctx, officeID)

	if len(ret) == 0 {
		panic("no return value specified for ListEmployees")
	}

	var r0 []employee_repository.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]employee_repository.Employee, error)); ok {
		return rf(ctx, officeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []employee_repository.Employee); ok {
		r0 = rf(ctx, officeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee_repository.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, officeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployee_ListEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEmployees'
type MockEmployee_ListEmployees_Call struct {
	*mock.Call
}

// ListEmployees is a helper method to define mock.On call
//   - ctx context.Context
//   - officeID int64
func (_e *MockEmployee_Expecter) ListEmployees(ctx interface{}, officeID interface{}) *MockEmployee_ListEmployees_Call {
	return &MockEmployee_ListEmployees_Call{Call: _e.mock.On("ListEmployees", ctx, officeID)}
}

func (_c *MockEmployee_ListEmployees_Call) Run(run func(ctx context.Context, officeID int64)) *MockEmployee_ListEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockEmployee_ListEmployees_Call) Return(_a0 []employee_repository.Employee, _a1 error) *MockEmployee_ListEmployees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployee_ListEmployees_Call) RunAndReturn(run func(context.Context, int64) ([]employee_repository.Employee, error)) *MockEmployee_ListEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// TransferEmployeeTx provides a mock function with given fields: ctx, arg
func (_m *MockEmployee) TransferEmployeeTx(ctx context.Context, arg employee_repository.EmployeeTransferTxParams) (employee_repository.EmployeeTransferTxResult, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for TransferEmployeeTx")
	}

	var r0 employee_repository.EmployeeTransferTxResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.EmployeeTransferTxParams) (employee_repository.EmployeeTransferTxResult, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.EmployeeTransferTxParams) employee_repository.EmployeeTransferTxResult); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(employee_repository.EmployeeTransferTxResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, employee_repository.EmployeeTransferTxParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmployee_TransferEmployeeTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferEmployeeTx'
type MockEmployee_TransferEmployeeTx_Call struct {
	*mock.Call
}

// TransferEmployeeTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg employee_repository.EmployeeTransferTxParams
func (_e *MockEmployee_Expecter) TransferEmployeeTx(ctx interface{}, arg interface{}) *MockEmployee_TransferEmployeeTx_Call {
	return &MockEmployee_TransferEmployeeTx_Call{Call: _e.mock.On("TransferEmployeeTx", ctx, arg)}
}

func (_c *MockEmployee_TransferEmployeeTx_Call) Run(run func(ctx context.Context, arg employee_repository.EmployeeTransferTxParams)) *MockEmployee_TransferEmployeeTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(employee_repository.EmployeeTransferTxParams))
	})
	return _c
}

func (_c *MockEmployee_TransferEmployeeTx_Call) Return(_a0 employee_repository.EmployeeTransferTxResult, _a1 error) *MockEmployee_TransferEmployeeTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmployee_TransferEmployeeTx_Call) RunAndReturn(run func(context.Context, employee_repository.EmployeeTransferTxParams) (employee_repository.EmployeeTransferTxResult, error)) *MockEmployee_TransferEmployeeTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmployee provides a mock function with given fields: ctx, arg
func (_m *MockEmployee) UpdateEmployee(ctx context.Context, arg employee_repository.UpdateEmployeeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, employee_repository.UpdateEmployeeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmployee_UpdateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmployee'
type MockEmployee_UpdateEmployee_Call struct {
	*mock.Call
}

// UpdateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - arg employee_repository.UpdateEmployeeParams
func (_e *MockEmployee_Expecter) UpdateEmployee(ctx interface{}, arg interface{}) *MockEmployee_UpdateEmployee_Call {
	return &MockEmployee_UpdateEmployee_Call{Call: _e.mock.On("UpdateEmployee", ctx, arg)}
}

func (_c *MockEmployee_UpdateEmployee_Call) Run(run func(ctx context.Context, arg employee_repository.UpdateEmployeeParams)) *MockEmployee_UpdateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(employee_repository.UpdateEmployeeParams))
	})
	return _c
}

func (_c *MockEmployee_UpdateEmployee_Call) Return(_a0 error) *MockEmployee_UpdateEmployee_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmployee_UpdateEmployee_Call) RunAndReturn(run func(context.Context, employee_repository.UpdateEmployeeParams) error) *MockEmployee_UpdateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmployee creates a new instance of MockEmployee. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmployee(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmployee {
	mock := &MockEmployee{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
