// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	office_repository "github.com/evgeny-tokarev/office_app/backend/internal/repositories/office_repository"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// AttachePhoto provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) AttachePhoto(ctx context.Context, arg office_repository.AttachePhotoParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AttachePhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, office_repository.AttachePhotoParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_AttachePhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachePhoto'
type MockQuerier_AttachePhoto_Call struct {
	*mock.Call
}

// AttachePhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - arg office_repository.AttachePhotoParams
func (_e *MockQuerier_Expecter) AttachePhoto(ctx interface{}, arg interface{}) *MockQuerier_AttachePhoto_Call {
	return &MockQuerier_AttachePhoto_Call{Call: _e.mock.On("AttachePhoto", ctx, arg)}
}

func (_c *MockQuerier_AttachePhoto_Call) Run(run func(ctx context.Context, arg office_repository.AttachePhotoParams)) *MockQuerier_AttachePhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(office_repository.AttachePhotoParams))
	})
	return _c
}

func (_c *MockQuerier_AttachePhoto_Call) Return(_a0 error) *MockQuerier_AttachePhoto_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_AttachePhoto_Call) RunAndReturn(run func(context.Context, office_repository.AttachePhotoParams) error) *MockQuerier_AttachePhoto_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOffice provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateOffice(ctx context.Context, arg office_repository.CreateOfficeParams) (office_repository.Office, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateOffice")
	}

	var r0 office_repository.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, office_repository.CreateOfficeParams) (office_repository.Office, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, office_repository.CreateOfficeParams) office_repository.Office); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(office_repository.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, office_repository.CreateOfficeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateOffice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOffice'
type MockQuerier_CreateOffice_Call struct {
	*mock.Call
}

// CreateOffice is a helper method to define mock.On call
//   - ctx context.Context
//   - arg office_repository.CreateOfficeParams
func (_e *MockQuerier_Expecter) CreateOffice(ctx interface{}, arg interface{}) *MockQuerier_CreateOffice_Call {
	return &MockQuerier_CreateOffice_Call{Call: _e.mock.On("CreateOffice", ctx, arg)}
}

func (_c *MockQuerier_CreateOffice_Call) Run(run func(ctx context.Context, arg office_repository.CreateOfficeParams)) *MockQuerier_CreateOffice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(office_repository.CreateOfficeParams))
	})
	return _c
}

func (_c *MockQuerier_CreateOffice_Call) Return(_a0 office_repository.Office, _a1 error) *MockQuerier_CreateOffice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateOffice_Call) RunAndReturn(run func(context.Context, office_repository.CreateOfficeParams) (office_repository.Office, error)) *MockQuerier_CreateOffice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOffice provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteOffice(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOffice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteOffice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOffice'
type MockQuerier_DeleteOffice_Call struct {
	*mock.Call
}

// DeleteOffice is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) DeleteOffice(ctx interface{}, id interface{}) *MockQuerier_DeleteOffice_Call {
	return &MockQuerier_DeleteOffice_Call{Call: _e.mock.On("DeleteOffice", ctx, id)}
}

func (_c *MockQuerier_DeleteOffice_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_DeleteOffice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQuerier_DeleteOffice_Call) Return(_a0 error) *MockQuerier_DeleteOffice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteOffice_Call) RunAndReturn(run func(context.Context, int64) error) *MockQuerier_DeleteOffice_Call {
	_c.Call.Return(run)
	return _c
}

// GetImagePath provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetImagePath(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImagePath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetImagePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImagePath'
type MockQuerier_GetImagePath_Call struct {
	*mock.Call
}

// GetImagePath is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) GetImagePath(ctx interface{}, id interface{}) *MockQuerier_GetImagePath_Call {
	return &MockQuerier_GetImagePath_Call{Call: _e.mock.On("GetImagePath", ctx, id)}
}

func (_c *MockQuerier_GetImagePath_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_GetImagePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQuerier_GetImagePath_Call) Return(_a0 string, _a1 error) *MockQuerier_GetImagePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetImagePath_Call) RunAndReturn(run func(context.Context, int64) (string, error)) *MockQuerier_GetImagePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetOffice provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetOffice(ctx context.Context, id int64) (office_repository.Office, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOffice")
	}

	var r0 office_repository.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (office_repository.Office, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) office_repository.Office); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(office_repository.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetOffice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOffice'
type MockQuerier_GetOffice_Call struct {
	*mock.Call
}

// GetOffice is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) GetOffice(ctx interface{}, id interface{}) *MockQuerier_GetOffice_Call {
	return &MockQuerier_GetOffice_Call{Call: _e.mock.On("GetOffice", ctx, id)}
}

func (_c *MockQuerier_GetOffice_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_GetOffice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockQuerier_GetOffice_Call) Return(_a0 office_repository.Office, _a1 error) *MockQuerier_GetOffice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetOffice_Call) RunAndReturn(run func(context.Context, int64) (office_repository.Office, error)) *MockQuerier_GetOffice_Call {
	_c.Call.Return(run)
	return _c
}

// ListOffices provides a mock function with given fields: ctx
func (_m *MockQuerier) ListOffices(ctx context.Context) ([]office_repository.Office, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOffices")
	}

	var r0 []office_repository.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]office_repository.Office, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []office_repository.Office); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]office_repository.Office)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListOffices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOffices'
type MockQuerier_ListOffices_Call struct {
	*mock.Call
}

// ListOffices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListOffices(ctx interface{}) *MockQuerier_ListOffices_Call {
	return &MockQuerier_ListOffices_Call{Call: _e.mock.On("ListOffices", ctx)}
}

func (_c *MockQuerier_ListOffices_Call) Run(run func(ctx context.Context)) *MockQuerier_ListOffices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_ListOffices_Call) Return(_a0 []office_repository.Office, _a1 error) *MockQuerier_ListOffices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListOffices_Call) RunAndReturn(run func(context.Context) ([]office_repository.Office, error)) *MockQuerier_ListOffices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOffice provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateOffice(ctx context.Context, arg office_repository.UpdateOfficeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOffice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, office_repository.UpdateOfficeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_UpdateOffice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOffice'
type MockQuerier_UpdateOffice_Call struct {
	*mock.Call
}

// UpdateOffice is a helper method to define mock.On call
//   - ctx context.Context
//   - arg office_repository.UpdateOfficeParams
func (_e *MockQuerier_Expecter) UpdateOffice(ctx interface{}, arg interface{}) *MockQuerier_UpdateOffice_Call {
	return &MockQuerier_UpdateOffice_Call{Call: _e.mock.On("UpdateOffice", ctx, arg)}
}

func (_c *MockQuerier_UpdateOffice_Call) Run(run func(ctx context.Context, arg office_repository.UpdateOfficeParams)) *MockQuerier_UpdateOffice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(office_repository.UpdateOfficeParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateOffice_Call) Return(_a0 error) *MockQuerier_UpdateOffice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_UpdateOffice_Call) RunAndReturn(run func(context.Context, office_repository.UpdateOfficeParams) error) *MockQuerier_UpdateOffice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
