// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package employee_repository

import (
	"context"
)

type Querier interface {
	AttachePhoto(ctx context.Context, arg AttachePhotoParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	DeleteEmployee(ctx context.Context, id int64) error
	// @sql postgresql
	GetEmployee(ctx context.Context, id int64) (Employee, error)
	GetImagePath(ctx context.Context, id int64) (string, error)
	ListEmployees(ctx context.Context, officeID int64) ([]Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
}

var _ Querier = (*Queries)(nil)
