// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user_repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int64          `db:"id"`
	Name              string         `db:"name"`
	Email             string         `db:"email"`
	Role              string         `db:"role"`
	HashedPassword    string         `db:"hashed_password"`
	PasswordChangedAt time.Time      `db:"password_changed_at"`
	CreatedAt         time.Time      `db:"created_at"`
	ImgFile           sql.NullString `db:"img_file"`
}
