// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user_repository

import (
	"context"
)

type Querier interface {
	AttachePhoto(ctx context.Context, arg AttachePhotoParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetImagePath(ctx context.Context, id int64) (string, error)
	// @sql postgresql
	GetUser(ctx context.Context, id int64) (User, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
