name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: db
          POSTGRES_DB: db
          POSTGRES_PASSWORD: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5458:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install sql-migrate
        working-directory: ./backend
        run: go install github.com/rubenv/sql-migrate/...@latest

      - name: Run migrations
        working-directory: ./backend
        run: make migrate-up

      - name: Debug Environment
        run: |
          pwd
          ls -al

      - name: Test
        working-directory: ./backend
        env:
          SERVER_PORT: 13005
          PG_PORT: 5458
          PG_HOST: 0.0.0.0
          PG_DB_NAME: db
          PG_USER: db
          PG_PWD: db
          LOG_LEVEL: DebugLevel

        run: go test -v -cover ./internal/repositories/...
